quarkus:
  log:
    level: INFO

  oidc:
    auth-server-url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:balhom-realm}
    client-id: ${KEYCLOAK_CLIENT_ID:balhom-client}
    application-type: service

  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USERNAME:}
    password: ${POSTGRES_PASSWORD:}
    jdbc:
      url: ${POSTGRES_URL}

  flyway:
    enabled: true
    migrate-at-start: true

  smallrye-openapi:
    enable: false

  swagger-ui:
    enable: false

  s3:
    endpoint-override: ${S3_URL}
    path-style-access: true
    sync-client:
      type: apache
    aws:
      region: ${S3_REGION:us-west-2}
      credentials:
        type: static
        static-provider:
          access-key-id: ${S3_ACCESS_KEY}
          secret-access-key: ${S3_SECRET_KEY}
    devservices:
      enabled: false

  rest-client:
    currency-profiles-api:
      url: http://localhost:8081
      scope: jakarta.inject.Singleton

s3:
  bucket:
    name: ${S3_BUCKET_NAME:balhom-bucket}

kafka:
  bootstrap:
    servers: ${KAFKA_SERVERS}

mp:
  messaging:
    outgoing:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
    incoming:
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: transaction-group
