quarkus:
  datasource:
    db-kind: postgresql

  s3:
    sync-client:
      type: apache
    devservices:
      enabled: true
      shared: true

s3:
  bucket:
    name: balhom-bucket

mp:
  messaging:
    outgoing:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
    incoming:
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: transaction-group
