quarkus:

  s3:
    sync-client:
      type: apache
    devservices:
      enabled: true
      shared: true
      buckets: balhom-api-bucket
    bucket:
      name: balhom-api-bucket

  rest-client:
    currency-profiles-api:
      url: http://test
      scope: javax.inject.Singleton

mp:
  messaging:
    outgoing:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
    incoming:
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: transaction-group
