name: API Build, Test and Upload to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Build
        run: |
          mvn package -B -DskipTests -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1-java21

      - name: Run tests
        run: |
          export QUARKUS_PROFILE=test
          mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          export APP_VERSION=$(grep '<version>' pom.xml | sed -n '1p' | tr -d ' ' | cut -d'>' -f2 | cut -d'<' -f1 | tr -d '\n' | tr -d '\r')
          echo "Using version ${APP_VERSION}"
          
          IMAGE_TAG="${DOCKER_REPO_NAME}:${APP_VERSION}"
          LATEST_TAG="${DOCKER_REPO_NAME}:latest"
          
          docker build -f src/main/docker/Dockerfile.native-micro -t ${IMAGE_TAG} .
          docker tag ${IMAGE_TAG} ${LATEST_TAG}
          
          docker push ${IMAGE_TAG}
          docker push ${LATEST_TAG}
        env:
          DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
